#!/usr/bin/env python3
"""
Prepare all pairwise NEB transition-pathway jobs between a set of reference
conformers (as produced by generate_reference_conformers.py with
--write-lammps-data), and emit a launcher script that runs each pair as a
multi-partition LAMMPS NEB job using neb_template.in.

For n reference conformers this generates C(n,2) pairs (n=15 -> 105 pairs,
matching the paper). Each pair gets its own working directory containing the
NEB "final coordinates" file (LAMMPS's required format for the `neb` command)
built directly from the target conformer's relaxed geometry -- atom ordering
is inherited unchanged from mol_common, so no re-indexing is needed.

Usage:
  python prepare_neb_pairs.py \\
      --conformer-dir refs_15 \\
      --output-dir neb_runs \\
      --lammps-bin lmp_mace --model-file mace-off-small.pt \\
      --n-images 30 --procs-per-image 1

This only WRITES the per-pair inputs and a launcher script; it does not run
LAMMPS itself. At 105 pairs x 30 partitions each, plan to submit these as a
cluster array job rather than running the generated bash script serially on
one node -- see the comment at the bottom of the generated launcher.
"""
import argparse
import glob
import itertools
import os
import re


def discover_conformers(conformer_dir):
    """Return a sorted list of (tag, data_path, xyz_path) for every
    conformer_NNN.{data,xyz} pair found in conformer_dir."""
    xyz_files = sorted(glob.glob(os.path.join(conformer_dir, "conformer_*.xyz")))
    conformers = []
    for xyz_path in xyz_files:
        tag = os.path.splitext(os.path.basename(xyz_path))[0]
        data_path = os.path.join(conformer_dir, f"{tag}.data")
        if not os.path.exists(data_path):
            raise FileNotFoundError(
                f"Missing {data_path} -- rerun generate_reference_conformers.py "
                f"with --write-lammps-data"
            )
        conformers.append((tag, data_path, xyz_path))
    if len(conformers) < 2:
        raise RuntimeError(f"Found only {len(conformers)} conformers in {conformer_dir}")
    return conformers


def write_neb_final_coords(xyz_path, out_path):
    """Write a LAMMPS `neb` command final-coordinates file:
        <N atoms>
        <blank line>
        id x y z
        id x y z
        ...
    Atom IDs are 1-indexed and MUST match the ordering in the corresponding
    LAMMPS data file (guaranteed here since both derive from the same
    mol_common-built geometry).
    """
    from ase.io import read

    atoms = read(xyz_path)
    with open(out_path, "w") as f:
        f.write(f"{len(atoms)}\n\n")
        for i, pos in enumerate(atoms.get_positions()):
            f.write(f"{i + 1} {pos[0]:.6f} {pos[1]:.6f} {pos[2]:.6f}\n")


def main():
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument(
        "--conformer-dir",
        required=True,
        help="Directory of conformer_NNN.{data,xyz} from generate_reference_conformers.py "
        "(run with --write-lammps-data)",
    )
    p.add_argument("--output-dir", required=True)
    p.add_argument("--template", default=os.path.join(os.path.dirname(__file__), "neb_template.in"))
    p.add_argument("--lammps-bin", required=True)
    p.add_argument(
        "--n-images",
        type=int,
        default=30,
        help="Total number of NEB replicas/partitions (paper discretizes each "
        "pathway into 30 images -- confirm whether that count already "
        "includes the two endpoints for your definition)",
    )
    p.add_argument("--procs-per-image", type=int, default=1)
    p.add_argument(
        "--pairs",
        default=None,
        help="Optional comma-separated list of 'i-j' pairs (0-indexed conformer "
        "ranks) to prepare instead of all C(n,2) pairs, e.g. for a SLURM "
        "array chunk: '0-1,0-2,1-2'",
    )

    args = p.parse_args()
    os.makedirs(args.output_dir, exist_ok=True)

    conformers = discover_conformers(args.conformer_dir)
    n = len(conformers)
    print(f"Found {n} reference conformers in {args.conformer_dir}")

    if args.pairs:
        pair_indices = []
        for tok in args.pairs.split(","):
            i, j = (int(x) for x in tok.split("-"))
            pair_indices.append((i, j))
    else:
        pair_indices = list(itertools.combinations(range(n), 2))

    print(f"Preparing {len(pair_indices)} NEB pair(s)...")

    launcher_path = os.path.join(args.output_dir, "run_neb_pairs.sh")
    with open(launcher_path, "w") as launcher:
        launcher.write("#!/usr/bin/env bash\n")
        launcher.write("# Auto-generated by prepare_neb_pairs.py\n")
        launcher.write("set -euo pipefail\n\n")

        for i, j in pair_indices:
            tag_i, data_i, xyz_i = conformers[i]
            tag_j, data_j, xyz_j = conformers[j]

            pair_dir = os.path.join(args.output_dir, f"pair_{i:03d}_{j:03d}")
            os.makedirs(pair_dir, exist_ok=True)

            final_coords_path = os.path.join(pair_dir, "final_coords.txt")
            write_neb_final_coords(xyz_j, final_coords_path)

            out_prefix = os.path.join(pair_dir, "pair")
            n_ranks = args.n_images * args.procs_per_image

            # NOTE: this direct `lmp -partition` invocation does NOT have
            # MACE-OFF available -- ML-IAP "unified" needs a Python driver to
            # register the model before the input script runs (see
            # mace_mliap_unified.py / run_md_python_driver.py), and an
            # MPI-partition-aware version of that driver has not been written
            # yet (see neb_template.in's "NOT YET RESOLVED" note). This
            # launcher is a placeholder until that driver exists.
            cmd = (
                f"mpirun -np {n_ranks} {args.lammps_bin} "
                f"-partition {args.n_images}x{args.procs_per_image} "
                f"-in {args.template} "
                f"-var init_data {data_i} "
                f"-var final_coords {final_coords_path} "
                f"-var out_prefix {out_prefix} "
                f"-log {pair_dir}/lammps.log"
            )
            launcher.write(f"echo 'Running pair {tag_i} -> {tag_j}'\n")
            launcher.write(cmd + "\n\n")

        launcher.write(
            "# NOTE: this script runs pairs SEQUENTIALLY. Each pair already uses "
            f"{args.n_images * args.procs_per_image} MPI ranks; running many pairs "
            "concurrently on a shared node will oversubscribe it. On a cluster, "
            "prefer submitting one pair per array-job task (use --pairs to chunk "
            "this script's output) rather than running this file directly.\n"
        )

    os.chmod(launcher_path, 0o755)
    print(f"Wrote {len(pair_indices)} pair director(ies) under {args.output_dir}/")
    print(f"Launcher script: {launcher_path}")


if __name__ == "__main__":
    main()
